### ISSUE TITLE
Support for multiple package tracking numbers per WooCommerce order

### ISSUE THREAD

**Issue by avishai** [AfterShip/aftership-apps-woocommerce#14]
How can I attach multiple shipment tracking numbers to the same order in WooCommerce? We often ship customer orders in more than one package, and it would be extremely helpful to add them all to the WC order and tracking page.

**Comment by aommm** [comment]
Sadly this feature is not currently on the roadmap. We will take your use case into consideration though. Thanks for the input!

**Comment by avishai** [comment]
I would be willing to develop this capability, as I need it for my project. Do you have any idea what the best way to start would be? I've created a fork at https://github.com/avishai/aftership-apps-woocommerce.

Thanks!

**Comment by dennispreston92** [comment]
This would be a great feature for AfterShip. A lot of people are using AfterShip to provide tracking for orders that are fulfilled by multiple AliExpress sellers and currently have to keep records of multiple tracking numbers themselves. This would become an essential feature of AfterShip.

**Comment by timkeen** [comment]
Hi! I'm yet another person who reallly needs this. Has there been any development progress? Thanks!

**Comment by rudeone** [comment]
need it too

**Comment by zggit** [comment]
No one? OMG.

**Comment by yangyao** [comment]
> No one? OMG.

We will consider adding this feature.
