### ISSUE TITLE
Česká Pošta missing from list of couriers

### ISSUE THREAD

**Issue by ahmed-sigmalux** [AfterShip/aftership-apps-woocommerce#18]
The WordPress plugin is missing Česká Pošta from the list of couriers.

**Comment by Bossa573** [comment]
https://github.com/AfterShip/aftership-apps-woocommerce/blob/master/assets/js/couriers.js#L341

Česká Pošta should be in the list, can you confirm?

**Comment by ahmed-sigmalux** [comment]
Yes, I found it. The problem was the special characters.
