### ISSUE TITLE
PHP Fatal error Failed opening required file 

### ISSUE THREAD

**Issue by rasikambaliya** [AfterShip/aftership-apps-woocommerce#185]
https://github.com/AfterShip/aftership-apps-woocommerce/blob/9b1ca4778c405a8939bf6bd26c3f374e5e83943a/aftership-woocommerce-tracking.php#L379

this line of code creating **PHP Fatal error:  require(): Failed opening required**

**Comment by briancwelch** [comment]
👍🏻
Confirmed the same issue on my end after latest update.

**Comment by briancwelch** [comment]
This issue is still not resolved.

**Comment by rasikambaliya** [comment]
Hi @yangyao 

I cannot not see any change in code and also there is no update to plugin so how you mark it as fixed ??

**Comment by yangyao** [comment]
@rasikambaliya Please check this line : https://github.com/AfterShip/aftership-apps-woocommerce/blob/master/aftership-woocommerce-tracking.php#L379
