### ISSUE TITLE
Hi @yangyao

### ISSUE THREAD

**Issue by rasikambaliya** [AfterShip/aftership-apps-woocommerce#187]
Hi @yangyao 

I cannot not see any change in code and also there is no update to plugin so how you mark it as fixed ??

_Originally posted by @rasikambaliya in https://github.com/AfterShip/aftership-apps-woocommerce/issues/185#issuecomment-1383884006_

**Comment by yangyao** [comment]
Ref to this link https://github.com/AfterShip/aftership-apps-woocommerce/blob/master/aftership-woocommerce-tracking.php#L379 @rasikambaliya
