### ISSUE TITLE
Why doesn't AfterShip sync TO WooCommerce?

### ISSUE THREAD

**Issue by ahmed-sigmalux** [AfterShip/aftership-apps-woocommerce#30]
We use AfterShip to manage tracking numbers and provide shipment notices for multiple sales channels. We want to do the same for WooCommerce, but the way this plugin works doesn't make sense. The plugin requires that we manually add tracking information to WooCommerce and then sync those manually added tracking numbers back to AfterShip.

Wouldn't it make far more sense for the plugin to import tracking numbers FROM AfterShip and TO WooCommerce? All of the tracking information has already been added to AfterShip via API, so why not import that to WooCommerce?

**Comment by SmoothMC** [comment]
Pushed!
Same Question here

**Comment by teddychan** [comment]
Thanks for the comment.
However, we don't have the plan for the user to create the tracking number in AfterShip, then sync back to any shopping cart.

One of the key reason is, we didn't store the `orders` in AfterShip.

To that say, we will consider adding such feature if we are able to store all the shopping carts' orders in AfterShip.
