### ISSUE TITLE
Please consider adding Pre/Post formatting options for track_message text for emails, even if just basic html tags.

### ISSUE THREAD

**Issue by abclution** [AfterShip/aftership-apps-woocommerce#46]
The tracking message inserted into the emails when sent to clients should be customizable to stand out more for readability. 

The way the code is currently setup, the only way I can change text format for the aftership strings is by editing the aftership.php

Having an formatting option (Pre / Post) for each track_message would be super helpful. Even if just to be able to put 

 `<h1></h1>`

$track_message_1 = $options['track_message_1'];
 $track_message_2 = $options['track_message_2'];
.................
 echo $track_message_1 . $values['aftership_tracking_provider_name'] . '<br/>' . $track_message_2 . $values['aftership_tracking_number'] . $required_fields_msg;

**Comment by yangyao** [comment]
> The tracking message inserted into the emails when sent to clients should be customizable to stand out more for readability.
> 
> The way the code is currently setup, the only way I can change text format for the aftership strings is by editing the aftership.php
> 
> Having an formatting option (Pre / Post) for each track_message would be super helpful. Even if just to be able to put
> 
> #
> $track_message_1 = $options['track_message_1'];
> $track_message_2 = $options['track_message_2'];
> .................
> echo $track_message_1 . $values['aftership_tracking_provider_name'] . '
> ' . $track_message_2 . $values['aftership_tracking_number'] . $required_fields_msg;

Thanks for your suggestion, we will consider adding this feature.

**Comment by FascistDonut** [comment]
It would also be cool to have the option of making the tracking number link to the aftership tracking page. Like:

` '<a href="https://'.$values['aftership_subdomain'].'.aftership.com/'.$values['aftership_tracking_number'] .'">' . $values['aftership_tracking_number'] .'</a>'`

(though that would also require adding a way to get the subdomain if there isn't one already)

**Comment by FascistDonut** [comment]
It would be good to be able to wrap the variables too, so we could make the tracking number a link to our branded aftership tracking page.
